In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np

In [3]:
# built in mathematical funtion 
# sigmoid

def sigmoid(array):
    return(1/ 1 + np.exp(-(array)))

a = np.arange(100)

sigmoid(a)

array([2.        , 1.36787944, 1.13533528, 1.04978707, 1.01831564,
       1.00673795, 1.00247875, 1.00091188, 1.00033546, 1.00012341,
       1.0000454 , 1.0000167 , 1.00000614, 1.00000226, 1.00000083,
       1.00000031, 1.00000011, 1.00000004, 1.00000002, 1.00000001,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [4]:
# loss funtion
# linear regreation -> mean square error

In [5]:
actual = np.random.randint(1,50,25)
predicted =  np.random.randint(1,50,25)

In [6]:
actual

array([48, 24, 10,  8,  9, 12, 38,  9, 22, 37, 49, 24, 18, 29, 25, 22, 10,
       16, 25, 36, 11, 40,  8,  7, 27])

In [7]:
predicted

array([14, 28, 10, 48, 24, 12, 36, 29, 45, 41, 21, 25, 17, 42, 22, 31, 31,
       23, 46, 30, 48,  4, 44,  4,  1])

In [8]:
def mse(actual,predicted):
   return  np.mean((actual -  predicted )**2)

mse(actual ,predicted)

np.float64(424.16)

In [9]:
# working with missing values ->np.nan
a = np.array([1,2,3,4,5,np.nan,6])
a

array([ 1.,  2.,  3.,  4.,  5., nan,  6.])

In [10]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 5., 6.])

In [11]:
# sorting